# Generated by Django 4.2.3 on 2024-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
