# Generated by Django 4.2.3 on 2024-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('Hydro', 'Hydroponics'), ('Container', ' Container Gardening'), ('Raised', 'Raised Beds'), ('Indoor', 'Indoor Gardens'), ('No', 'No Category')], default='No Category', max_length=100),
        ),
    ]
