# Generated by Django 4.2.3 on 2024-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('Raised', 'Raised Beds'), ('Container', ' Container Gardening'), ('Hydro', 'Hydroponics'), ('No', 'No Category'), ('Indoor', 'Indoor Gardens')], default='No Category', max_length=100),
        ),
    ]
