# Generated by Django 4.2.3 on 2024-01-26 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_alter_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('Indoor', 'Indoor Gardens'), ('Hydro', 'Hydroponics'), ('Raised', 'Raised Beds'), ('No', 'No Category'), ('Container', ' Container Gardening')], default='No Category', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
        ),
    ]
