# Generated by Django 4.2.3 on 2024-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_categories_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('Indoor', 'Indoor Gardens'), ('Container', ' Container Gardening'), ('Raised', 'Raised Beds'), ('No', 'No Category'), ('Hydro', 'Hydroponics')], default='No Category', max_length=100),
        ),
    ]
